version: "3"

services:
  database:
    build: ./database
    container_name: database
    volumes:
      - ./database/backup/:/docker-entrypoint-initdb.d/
      - ./database/data:/var/lib/postgresql/data
    ports:
      - 5433:5432
